package spinal.xilinx.reports

import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import spinal.core.{Clock => _, _}   // import all of spinal.core except Clock (shadows our Clock)
import spinal.lib._
import java.nio.file.Files
import scala.io.Source

class TclGenerationSpec extends AnyFlatSpec with Matchers {

  class SimplePassThrough extends Component {
    val io = new Bundle {
      val clk = in Bool ()
      val a   = in  UInt(8 bits)
      val b   = out UInt(8 bits)
    }
    noIoPrefix()  // ports are named clk/a/b (not io_clk/io_a/io_b) — required to match Clock names
    io.b := io.a
  }

  private def tmpDir(): String = {
    val d = Files.createTempDirectory("spinal_tcl_test_").toFile
    d.deleteOnExit()
    d.getAbsolutePath
  }

  private def readFile(path: String): String = {
    val src = Source.fromFile(path)
    try src.mkString finally src.close()
  }

  "Project.create" should "generate a valid TCL file" in {
    val outDir = tmpDir()
    val clocks = Seq(Clock.fromMhz("clk", 250.0))
    val handle = Project.create(
      factory  = () => new SimplePassThrough,
      clocks   = clocks,
      partName = "xcvu9p-flbg2104-2-e",
      outputPath = outDir
    )

    val tcl = readFile(handle.tclFile)
    tcl should include ("# Synthesis script generated by spinal_xilinx_reports")
    tcl should include ("create_project -in_memory -part xcvu9p-flbg2104-2-e")
    tcl should include ("synth_design -top SimplePassThrough -mode out_of_context")
    tcl should include ("auto_detect_xpm")
    tcl should include ("""set_param synth.elaboration.rodinMoreOptions "rt::set_parameter synRetiming true"""")
  }

  it should "emit CLB utilization query" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xcvu9p",
      outputPath = outDir
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("""PRIMITIVE_GROUP == "CLB"""")
    tcl should include ("""GROUP CLB $v_CLB""")
  }

  it should "include PRIMITIVE_LEVEL != MACRO filter for LUTRAM" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xcvu9p",
      outputPath = outDir
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("""PRIMITIVE_LEVEL != "MACRO"""")
  }

  it should "NOT include PRIMITIVE_LEVEL filter for LUT" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xcvu9p",
      outputPath = outDir
    )
    val tcl = readFile(handle.tclFile)
    // Find the LUT line and verify it has no MACRO filter
    val lutLine = tcl.split("\n").find(l => l.contains("PRIMITIVE_SUBGROUP") && l.contains("""== "LUT"""")).get
    lutLine should not include ("PRIMITIVE_LEVEL")
  }

  it should "emit timing queries for each clock" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Seq(Clock.fromMhz("clk", 250.0)),
      partName   = "xcvu9p",
      outputPath = outDir
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("""NAME == "clk"""")
    tcl should include ("get_timing_paths -from $clock -to $clock -max_paths 1 -nworst 1 -setup")
    tcl should include ("""TIMING clk $setup $hold""")
  }

  it should "generate a valid XDC file with create_clock" in {
    val outDir = tmpDir()
    Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Seq(Clock.fromMhz("clk", 250.0)),
      partName   = "xcvu9p",
      outputPath = outDir
    )
    val xdcPath = outDir + "/SimplePassThrough.xdc"
    val xdc = readFile(xdcPath)
    xdc should include ("create_clock")
    xdc should include ("-name \"clk\"")
    xdc should include ("-period 4.000")
  }

  it should "include -flatten_hierarchy none when preserveHierarchy = true" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory           = () => new SimplePassThrough,
      clocks            = Nil,
      partName          = "xcvu9p",
      outputPath        = outDir,
      preserveHierarchy = true
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("-flatten_hierarchy none")
  }

  it should "NOT include -flatten_hierarchy when preserveHierarchy = false" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xcvu9p",
      outputPath = outDir
    )
    val tcl = readFile(handle.tclFile)
    tcl should not include "-flatten_hierarchy"
  }

  it should "include place_design and route_design when requested" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xcvu9p",
      outputPath = outDir,
      place      = true,
      route      = true
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("place_design")
    tcl should include ("route_design")
    tcl should include ("""write_reports "post_place"""")
    tcl should include ("""write_reports "post_route"""")
    handle.reportFile should include ("post_route")
  }

  it should "use get_cells (no -hier) when reportHierarchy = false" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xcvu9p",
      outputPath = outDir,
      config     = ProjectConfig(reportHierarchy = false)
    )
    val tcl = readFile(handle.tclFile)
    val queriesSection = tcl.split("proc write_reports")(1)
    queriesSection should not include ("get_cells -hier")
    queriesSection should include ("get_cells -filter")
  }

  "Spartan7 family config" should "emit 7-series PRIMITIVE_GROUP names" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xc7s50csga324-1",
      outputPath = outDir,
      config     = ProjectConfig(primitiveGroups = DeviceFamily.Spartan7.defaultPrimitiveGroups)
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("""PRIMITIVE_GROUP == "LUT"""")
    tcl should include ("""PRIMITIVE_GROUP == "FLOP_LATCH"""")
    tcl should include ("""PRIMITIVE_GROUP == "BMEM"""")
    tcl should include ("""PRIMITIVE_GROUP == "DMEM"""")
  }

  it should "use lowercase subgroup names" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xc7s50csga324-1",
      outputPath = outDir,
      config     = ProjectConfig(primitiveGroups = DeviceFamily.Spartan7.defaultPrimitiveGroups)
    )
    val tcl = readFile(handle.tclFile)
    tcl should include ("""PRIMITIVE_SUBGROUP == "flop"""")
    tcl should include ("""PRIMITIVE_SUBGROUP == "bram"""")
    tcl should include ("""PRIMITIVE_SUBGROUP == "fifo"""")
    tcl should include ("""PRIMITIVE_SUBGROUP == "dram"""")
  }

  it should "not emit UltraScale-only group names" in {
    val outDir = tmpDir()
    val handle = Project.create(
      factory    = () => new SimplePassThrough,
      clocks     = Nil,
      partName   = "xc7s50csga324-1",
      outputPath = outDir,
      config     = ProjectConfig(primitiveGroups = DeviceFamily.Spartan7.defaultPrimitiveGroups)
    )
    val tcl = readFile(handle.tclFile)
    tcl should not include ("""PRIMITIVE_GROUP == "CLB"""")
    tcl should not include ("""PRIMITIVE_GROUP == "REGISTER"""")
    tcl should not include ("""PRIMITIVE_SUBGROUP == "URAM"""")
  }
}
