package spinal.xilinx.reports

import spinal.core.{Component, SpinalConfig}
import java.io.{File, PrintWriter}
import scala.sys.process.{Process, ProcessLogger}

case class ProjectConfig(
  vivadoUtilizationReport: Boolean             = false,
  vivadoTimingReport:      Boolean             = false,
  primitiveGroups:         Seq[PrimitiveGroup] = PrimitiveGroup.default,
  fullDesignHierarchy:     Boolean             = false,
  optDesign:               Option[Boolean]     = None,
  reportHierarchy:         Boolean             = true,
  retiming:                Boolean             = true
)

case class ProjectHandle(tclFile: String, reportFile: String, outputPath: String)

object Project {

  def create(
    factory:           () => Component,
    clocks:            Seq[Clock],
    partName:          String,
    outputPath:        String,
    config:            ProjectConfig = ProjectConfig(),
    place:             Boolean       = false,
    route:             Boolean       = false,
    checkpoint:        Boolean       = false,
    preserveHierarchy: Boolean       = false
  ): ProjectHandle = {
    new File(outputPath).mkdirs()

    val spinalCfg = SpinalConfig(targetDirectory = outputPath, verbose = false)
    val spinalReport = spinalCfg.generateVerilog(factory())
    val topName = spinalReport.toplevel.definitionName

    // Only constrain clocks that appear as input ports on this module
    val ioNames = spinalReport.toplevel.getAllIo.map(_.getName()).toSet
    val filteredClocks = clocks.filter(c => ioNames.contains(c.name))

    writeXdc(s"$outputPath/$topName.xdc", filteredClocks)

    val reportBase = s"$outputPath/report.txt"
    writeTcl(
      tclPath           = s"$outputPath/$topName.tcl",
      topName           = topName,
      outputPath        = outputPath,
      partName          = partName,
      verilogFileName   = s"$topName.v",
      xdcFileName       = s"$topName.xdc",
      reportBase        = reportBase,
      clocks            = filteredClocks,
      config            = config,
      place             = place,
      route             = route,
      checkpoint        = checkpoint,
      preserveHierarchy = preserveHierarchy
    )

    val reportFile = (place, route) match {
      case (_, true) => s"$outputPath/post_route_report.txt"
      case (true, _) => s"$outputPath/post_place_report.txt"
      case _         => s"$outputPath/post_synth_report.txt"
    }
    ProjectHandle(s"$outputPath/$topName.tcl", reportFile, outputPath)
  }

  def run(
    handle:       ProjectHandle,
    verbose:      Boolean = false,
    pathToVivado: String  = "vivado"
  ): Option[Report] = {
    val cmd = Seq(pathToVivado, "-mode", "batch", "-nolog", "-nojournal", "-source", handle.tclFile)
    val logger =
      if (verbose) ProcessLogger(System.out.println, System.err.println)
      else         ProcessLogger(_ => (), _ => ())
    val exitCode = Process(cmd).!(logger)
    if (exitCode == 0) Some(Report.read(handle.reportFile)) else None
  }

  // ── XDC ──────────────────────────────────────────────────────────────

  private def writeXdc(path: String, clocks: Seq[Clock]): Unit = {
    val pw = new PrintWriter(new File(path))
    try {
      pw.println("# Clock constraints")
      clocks.foreach { clk =>
        pw.println(f"""create_clock -name "${clk.name}" -period ${clk.period}%.3f [get_ports "${clk.name}"]""")
        clk.clkSrcBufg.foreach { src =>
          pw.println(s"""set_property HD.CLK_SRC $src [get_ports "${clk.name}"]""")
        }
      }
    } finally pw.close()
  }

  // ── TCL ──────────────────────────────────────────────────────────────

  private def writeTcl(
    tclPath:           String,
    topName:           String,
    outputPath:        String,
    partName:          String,
    verilogFileName:   String,
    xdcFileName:       String,
    reportBase:        String,
    clocks:            Seq[Clock],
    config:            ProjectConfig,
    place:             Boolean,
    route:             Boolean,
    checkpoint:        Boolean,
    preserveHierarchy: Boolean
  ): Unit = {
    val pw = new PrintWriter(new File(tclPath))
    try {
      pw.println("# Synthesis script generated by spinal_xilinx_reports")

      // ── synthesize proc ──────────────────────────────────────────────
      pw.println("proc synthesize { root } {")
      pw.println(s"create_project -in_memory -part $partName")
      pw.println(s"read_verilog [file join $$root $verilogFileName]")
      pw.println(s"read_xdc [file join $$root $xdcFileName]")
      pw.println(s"set_property top $topName [current_fileset]")
      pw.println("auto_detect_xpm")
      if (config.retiming)
        pw.println("""set_param synth.elaboration.rodinMoreOptions "rt::set_parameter synRetiming true"""")
      val flattenFlag = if (preserveHierarchy) " -flatten_hierarchy none" else ""
      pw.println(s"synth_design -top $topName -mode out_of_context$flattenFlag")
      if (checkpoint)
        pw.println(s"""write_checkpoint -force "$outputPath/post_synth.dcp"""")
      val runOpt = config.optDesign match {
        case Some(v) => v
        case None    => config.fullDesignHierarchy
      }
      if (runOpt) pw.println("opt_design")
      pw.println("}")

      // ── write_reports proc ───────────────────────────────────────────
      pw.println("proc write_reports { stage root } {")
      if (config.vivadoUtilizationReport)
        pw.println(s"""report_utilization -file [file join $$root "$${stage}_$topName.utilization"]""")
      if (config.vivadoTimingReport)
        pw.println(s"""report_timing_summary -file [file join $$root "$${stage}_$topName.timing"]""")
      pw.println(s"""set report_file [open [file join $$root "$${stage}_report.txt"] "w"]""")
      pw.println("current_instance")
      emitUtilizationQueries(pw, config)
      emitTimingQueries(pw, clocks)
      pw.println("close $report_file")
      pw.println("}")

      // ── invocations ──────────────────────────────────────────────────
      pw.println(s"""synthesize "$outputPath"""")
      pw.println(s"""write_reports "post_synth" "$outputPath"""")
      if (place) {
        pw.println("place_design")
        pw.println(s"""write_reports "post_place" "$outputPath"""")
        if (checkpoint)
          pw.println(s"""write_checkpoint -force "$outputPath/post_place.dcp"""")
      }
      if (route) {
        pw.println("route_design")
        pw.println(s"""write_reports "post_route" "$outputPath"""")
        if (checkpoint)
          pw.println(s"""write_checkpoint -force "$outputPath/post_route.dcp"""")
      }
    } finally pw.close()
  }

  private def emitUtilizationQueries(pw: PrintWriter, config: ProjectConfig): Unit = {
    val getCells = if (config.reportHierarchy) "get_cells -hier" else "get_cells"
    config.primitiveGroups.foreach { pg =>
      val gName = pg.primitiveGroup
      pw.println(s"""set v_$gName [llength [$getCells -filter {PRIMITIVE_GROUP == "$gName"}]]""")
      pw.println(s"""puts $$report_file "GROUP $gName $$v_$gName"""")
      pg.subgroups.foreach { sg =>
        val sName = sg.primitiveSubgroup
        val macroFilter =
          if (sg.ignoreMacroPrimitives) """ && PRIMITIVE_LEVEL != "MACRO"""" else ""
        pw.println(
          s"""set v_${gName}_$sName [llength [$getCells -filter {PRIMITIVE_GROUP == "$gName" && PRIMITIVE_SUBGROUP == "$sName"$macroFilter}]]"""
        )
        pw.println(s"""puts $$report_file "SUBGROUP $gName:$sName $$v_${gName}_$sName"""")
      }
    }
  }

  private def emitTimingQueries(pw: PrintWriter, clocks: Seq[Clock]): Unit = {
    clocks.foreach { clk =>
      val n = clk.name
      // language=TCL
      pw.println(
        s"""set setup 0
set hold 0
set clock [get_clocks -filter {NAME == "$n"}]
if { [llength $$clock] == 1 } {
  set timing_path [get_timing_paths -from $$clock -to $$clock -max_paths 1 -nworst 1 -setup]
  if { [llength $$timing_path] == 1 } {
    set setup [get_property SLACK $$timing_path]
  }
  set timing_path [get_timing_paths -from $$clock -to $$clock -max_paths 1 -nworst 1 -hold]
  if { [llength $$timing_path] == 1 } {
    set hold [get_property SLACK $$timing_path]
  }
}
puts $$report_file "TIMING $n $$setup $$hold"""")
    }
  }
}
